version: '3'

services:
  aquila-db:
    image: postgres:10.4
    volumes:
      - aquiladb:/var/lib/postgresql/data/
  aquila-web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8009"
    depends_on:
      - aquila-db

volumes:
  aquiladb:
