services:
  aquila-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    command: /var/www/aquila/entrypoint.dev.sh
    environment:
      - APPLICATION_PORT=8081
      - DJANGO_SECRET_KEY=
      - DJANGO_DEBUG=
      - DJANGO_ALLOWED_HOSTS=
      - SQL_ENGINE=
      - SQL_DATABASE=
      - SQL_USER=
      - SQL_PASSWORD=
      - SQL_HOST=
      - SQL_PORT=5432
      - LOGIN_URL=/microsoft_authentication/login
      - LOGOUT_URL=/
      - MTM_ID=
      - MS_APP_ID=
      - MS_APP_SECRET=
      - MS_APP_REDIRECT=
      - MS_APP_SCOPES=
      - MS_APP_AUTHORITY=
      - MS_APP_VALID_EMAIL_DOMAINS=
      - MS_APP_LOGOUT_URI=
    hostname: ${HOSTNAME}
    volumes:
      - .:/var/www/aquila
