version: '3'

services:
  aquila-db:
    image: postgres:10.4
    volumes:
      - aquiladb:/var/lib/postgresql/data/
  aquila-web:
    build: .
    entrypoint: /code/entrypoint.sh
    environment:
      - APPLICATION_PORT=${APPLICATION_PORT:-8009}
    volumes:
      - .:/code
    ports:
      - "${APPLICATION_PORT:-8009}:${APPLICATION_PORT:-8009}"
    depends_on:
      - aquila-db

volumes:
  aquiladb:
