# Generated by Django 3.2.5 on 2021-08-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assign_rights', '0001_squashed_0006_auto_20210409_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rightsshell',
            old_name='license_terms',
            new_name='terms',
        ),
    ]
