# Generated by Django 2.2.13 on 2020-07-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_rights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rightsshell',
            name='rights_id',
        ),
        migrations.AddField(
            model_name='rightsshell',
            name='jurisdiction',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='rightsshell',
            name='copyright_status',
            field=models.CharField(blank=True, choices=[('copyrighted', 'copyrighted'), ('public domain', 'public domain'), ('unknown', 'unknown')], max_length=64, null=True),
        ),
    ]
