# Generated by Django 2.2.13 on 2020-07-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assign_rights', '0002_auto_20200707_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rightsshell',
            old_name='applicable_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='rightsshell',
            old_name='applicable_start_date',
            new_name='start_date',
        ),
    ]
