# Generated by Django 3.2.5 on 2021-08-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assign_rights', '0002_rename_license_terms_rightsshell_terms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rightsgranted',
            old_name='note',
            new_name='granted_note',
        ),
        migrations.RenameField(
            model_name='rightsshell',
            old_name='note',
            new_name='basis_note',
        ),
    ]
