# Generated by Django 5.2.7 on 2025-11-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_rights', '0003_auto_20210820_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightsshell',
            name='copyright_status',
            field=models.CharField(blank=True, choices=[('copyrighted', 'copyrighted'), ('public_domain', 'public_domain'), ('unknown', 'unknown')], max_length=64, null=True),
        ),
    ]
