# Generated by Django 2.2.13 on 2020-07-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_rights', '0003_auto_20200709_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightsgranted',
            name='end_date_period',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rightsgranted',
            name='start_date_period',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rightsshell',
            name='end_date_period',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rightsshell',
            name='start_date_period',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
