# Generated by Django 2.2.13 on 2020-10-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_rights', '0004_auto_20200710_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightsshell',
            name='end_date_open',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rightsshell',
            name='end_date_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rightsshell',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
