# Generated by Django 3.1.7 on 2021-04-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_rights', '0005_auto_20201006_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouping',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rightsgranted',
            name='end_date_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rightsgranted',
            name='start_date_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rightsshell',
            name='end_date_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rightsshell',
            name='note',
            field=models.TextField(default='note'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rightsshell',
            name='rights_basis',
            field=models.CharField(choices=[('copyright', 'Copyright'), ('statute', 'Statute'), ('license', 'License'), ('policy', 'Policy'), ('donor', 'Donor')], max_length=64),
        ),
        migrations.AlterField(
            model_name='rightsshell',
            name='start_date_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
