# Generated by Django 2.2.13 on 2020-10-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_rights', '0005_auto_20201006_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightsgranted',
            name='end_date_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rightsgranted',
            name='start_date_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rightsshell',
            name='end_date_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rightsshell',
            name='start_date_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
