# Generated by Django 2.2.13 on 2021-02-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_rights', '0006_auto_20201007_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightsshell',
            name='rights_basis',
            field=models.CharField(choices=[('Copyright', 'Copyright'), ('Statute', 'Statute'), ('License', 'License'), ('Policy', 'Policy'), ('Donor', 'Donor'), ('Other', 'Other')], max_length=64),
        ),
    ]
