# Generated by Django 3.1.7 on 2021-03-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_rights', '0009_auto_20210303_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouping',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rightsshell',
            name='note',
            field=models.TextField(default='sometext'),
            preserve_default=False,
        ),
    ]
