# Generated by Django 3.1.7 on 2021-03-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_rights', '0010_auto_20210324_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouping',
            name='description',
            field=models.TextField(),
        ),
    ]
